AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ''

Resources:
  HelloNameFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'hello-name-function'
      Description: ''
      CodeUri: .
      Handler: 'src/helloName.php'
      Timeout: 10 # Timeout in seconds
      MemorySize: 1024 # The memory size is related to the pricing and CPU power
      Runtime: provided
      Layers:
        - 'arn:aws:lambda:eu-west-1:209497400698:layer:php-72:3'
  Console:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'shopify-products-console'
      CodeUri: .
      Handler: ./shopify-products # or `artisan` for Laravel
      Runtime: provided
      Layers:
      # PHP runtime
      - 'arn:aws:lambda:eu-west-1:209497400698:layer:php-72:3'
      # Console layer
      - 'arn:aws:lambda:eu-west-1:209497400698:layer:console:3'